apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-luzq
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0029-tenant/tkwch-fix-0075-0029-app/devfile-sample-luzq@sha256:d3c1c3d4e6ae9307d16f4f058c7ada5fae87a5bcd3b7f340760bc7f36cb8c20e
        name: my-nodejs
        resources: {}
status: {}
